dic_color = {'indigo': '#4B0082',
             'gold': '#FFD700',
             'firebrick': '#B22222',
             'indianred': '#CD5C5C',
             'yellow': '#FFFF00',
             'darkolivegreen': '#556B2F',
             'darkseagreen': '#8FBC8F',
             'slategrey': '#708090',
             'darkorange': '#FF8C00',
             'darkslategrey': '#2F4F4F',
             'mediumvioletred': '#C71585',
             'mediumorchid': '#BA55D3',
             'papayawhip': '#FFEFD5',
             'mediumslateblue': '#7B68EE',
             # 'black': '#000000',
             'springgreen': '#00FF7F',
             'orange': '#FFA500',
             'lightsalmon': '#FFA07A',
             'brown': '#A52A2A',
             'turquoise': '#40E0D0',
             'olivedrab': '#6B8E23',
             'lightcyan': '#E0FFFF',
             'cyan': '#00FFFF',
             'silver': '#C0C0C0',
             'skyblue': '#87CEEB',
             'gray': '#808080',
             'darkturquoise': '#00CED1',
             'goldenrod': '#DAA520',
             'darkgreen': '#006400',
             'darkviolet': '#9400D3',
             'darkgray': '#A9A9A9',
             'lightpink': '#FFB6C1',
             'teal': '#008080',
             'darkmagenta': '#8B008B',
             'lightgoldenrodyellow': '#FAFAD2',
             'lavender': '#E6E6FA',
             'yellowgreen': '#9ACD32',
             'thistle': '#D8BFD8',
             'violet': '#EE82EE',
             # 'navy': '#000080',
             # 'dimgrey': '#696969',
             'orchid': '#DA70D6',
             'blue': '#0000FF',
             'ghostwhite': '#F8F8FF',
             'honeydew': '#F0FFF0',
             'cornflowerblue': '#6495ED',
             ##'darkblue': '#00008B',
             'coral': '#FF7F50',
             # 'darkkhaki': '#BDB76B',
             'mediumpurple': '#9370DB',
             'cornsilk': '#FFF8DC',
             'red': '#FF0000',
             'bisque': '#FFE4C4',
             'slategray': '#708090',
             # 'darkcyan': '#008B8B',
             'khaki': '#F0E68C',
             'wheat': '#F5DEB3',
             'deepskyblue': '#00BFFF',
             # 'rebeccapurple': '#663399',
             # 'darkred': '#8B0000',
             'steelblue': '#4682B4',
             'aliceblue': '#F0F8FF',
             'lightslategrey': '#778899',
             'gainsboro': '#DCDCDC',
             'mediumturquoise': '#48D1CC',
             # 'g': '(0, 0.5, 0)',
             # 'k': '(0, 0, 0)',
             'purple': '#800080',
             'lightgrey': '#D3D3D3',
             'burlywood': '#DEB887',
             # 'darksalmon': '#E9967A',
             'beige': '#F5F5DC',
             'azure': '#F0FFFF',
             'lightsteelblue': '#B0C4DE',
             'oldlace': '#FDF5E6',
             'greenyellow': '#ADFF2F',
             'royalblue': '#4169E1',
             'lightseagreen': '#20B2AA',
             'sienna': '#A0522D',
             'lightcoral': '#F08080',
             'orangered': '#FF4500',
             'navajowhite': '#FFDEAD',
             'lime': '#00FF00',
             'palegreen': '#98FB98',
             'mistyrose': '#FFE4E1',
             'seashell': '#FFF5EE',
             'mediumspringgreen': '#00FA9A',
             'fuchsia': '#FF00FF',
             'chartreuse': '#7FFF00',
             'blanchedalmond': '#FFEBCD',
             'peru': '#CD853F',
             'aquamarine': '#7FFFD4',
             'white': '#FFFFFF',
             'darkslategray': '#2F4F4F',
             'lightgray': '#D3D3D3',
             'ivory': '#FFFFF0',
             'darkgoldenrod': '#B8860B',
             'lawngreen': '#7CFC00',
             'chocolate': '#D2691E',
             'crimson': '#DC143C',
             'forestgreen': '#228B22',
             'darkgrey': '#A9A9A9',
             'olive': '#808000',
             'mintcream': '#F5FFFA',
             'antiquewhite': '#FAEBD7',
             'floralwhite': '#FFFAF0',
             'moccasin': '#FFE4B5',
             'limegreen': '#32CD32',
             # 'saddlebrown': '#8B4513',
             'grey': '#808080',
             'darkslateblue': '#483D8B',
             'lightskyblue': '#87CEFA',
             'deeppink': '#FF1493',
             'plum': '#DDA0DD',
             'cadetblue': '#5F9EA0',
             'dodgerblue': '#1E90FF',
             # 'maroon': '#800000',
             'sandybrown': '#F4A460',
             'aqua': '#00FFFF',
             'magenta': '#FF00FF',
             'tan': '#D2B48C',
             'rosybrown': '#BC8F8F',
             'pink': '#FFC0CB',
             'lightblue': '#ADD8E6',
             'palevioletred': '#DB7093',
             'mediumseagreen': '#3CB371',
             'slateblue': '#6A5ACD',
             # 'dimgray': '#696969',
             'powderblue': '#B0E0E6',
             'seagreen': '#2E8B57',
             'snow': '#FFFAFA',
             # 'mediumblue': '#0000CD',
             # 'midnightblue': '#191970',
             'paleturquoise': '#AFEEEE',
             'palegoldenrod': '#EEE8AA',
             'whitesmoke': '#F5F5F5',
             'darkorchid': '#9932CC',
             'salmon': '#FA8072',
             'lightslategray': '#778899',
             'lemonchiffon': '#FFFACD',
             'lightgreen': '#90EE90',
             'tomato': '#FF6347',
             'hotpink': '#FF69B4',
             'lightyellow': '#FFFFE0',
             'lavenderblush': '#FFF0F5',
             'linen': '#FAF0E6',
             'mediumaquamarine': '#66CDAA',
             # 'green': '#008000',
             'blueviolet': '#8A2BE2',
             'peachpuff': '#FFDAB9',
             }

import random


class colors(object):
  def __init__(self):
    self.colors = dic_color
    self.random = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F']

  def get_random_color(self):
    color_list = list(self.colors.keys())
    if len(self.colors) > 1:
      index = random.randint(0, len(self.colors) - 1)
      c = color_list[index]
      self.colors.pop(c)
      return c
    else:
      tmp = random.sample(self.random, 6)
      tmp.insert(0, '#')
      return ''.join(tmp)

if __name__ == "__main__":
  c = colors()
  for i in range(150):
    print(c.get_random_color())
